#!/usr/bin/env python3
"""ACL-02 真实场景：Human Takeover 期间手工改文件后恢复.

场景：
  1. Agent 在 workspace 中创建并修改文件
  2. 人工接管 (take_over) — 在任务完成前触发
  3. 人在磁盘上直接编辑文件（不同的内容）
  4. Agent 恢复 (resume)，继续工作
  5. 验证：Agent 不暴力覆盖人工修改

这个测试涉及真实文件系统操作，不是 state.facts 模拟。
"""

import asyncio
import os
import sys
import tempfile
import traceback
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))

from forge.kernel.runtime import Runtime
from forge.kernel.event_bus import Event, EventKind, event_bus

PASS = 0
FAIL = 0


def check(name: str, condition: bool, detail: str = ""):
    global PASS, FAIL
    if condition:
        PASS += 1
        print(f"  [PASS] {name}")
    else:
        FAIL += 1
        print(f"  [FAIL] {name} -- {detail}")


async def test_acl02_real_takeover():
    """ACL-02 真实文件接管测试.

    Agent 在 temp workspace 中改文件 → 人接管 → 人改文件 → resume.
    """
    print("\n" + "=" * 64)
    print("ACL-02 (Real): Human Takeover — 真实文件接管")
    print("=" * 64)

    # ── 1. Setup: temp workspace with a file ──
    workspace = Path(tempfile.mkdtemp(prefix="acl02_ws_"))
    target_file = workspace / "app.py"

    # Agent 初始内容（会被它的 handler 追加写，不会覆盖）
    SEED = "# app.py — Auto-generated by ForgeX Agent\n"
    AGENT_LINE = "def agent_tool():\n    pass\n"
    HUMAN_CONTENT = f"""# app.py — Human override
def hello():
    print("hello from human — this must survive!")

if __name__ == "__main__":
    hello()
    print("human edit: added debug line")
"""
    target_file.write_text(SEED, encoding="utf-8")
    print(f"\n  [Setup] Workspace: {workspace}")
    print(f"  [Setup] File: {target_file}")
    print(f"  [Setup] Seed written ({len(SEED)} chars)")

    # ── 2. Start Runtime with file-modifying handlers ──
    rt = Runtime(token_budget=100000, round_limit=30)

    async def plan(state):
        for i in range(3):
            await asyncio.sleep(0.15)
            state.add_fact(f"plan_{i}")

    async def explore(state):
        for i in range(3):
            await asyncio.sleep(0.15)
            state.add_fact(f"explore_{i}")

    async def implement(state):
        """Agent 以 append 模式改文件（不覆盖）。"""
        await asyncio.sleep(0.15)
        with target_file.open("a", encoding="utf-8") as f:
            f.write(f"\n# Agent round {state.round}\n")
            f.write("def agent_func():\n")
            f.write("    return 'agent_work'\n")
        state.add_change(f"agent_modified_round_{state.round}")
        state.add_fact(f"agent_wrote_round_{state.round}")

    async def verify(state):
        state.add_fact("verified")

    rt.on_plan(plan)
    rt.on_explore(explore)
    rt.on_implement(implement)
    rt.on_verify(verify)

    # ── 3. 双 collector 策略 ──
    #  main_collector: 捕获所有事件（包括 takeover/resume）
    #  秘诀：不依赖 subscribe() 的 TASK_COMPLETED break，用 aiter 手动控制
    events: list[Event] = []
    stop_signal = asyncio.Event()

    async def main_collector():
        q = asyncio.Queue(maxsize=256)
        event_bus._subscribers.add(q)
        try:
            while True:
                try:
                    ev = await asyncio.wait_for(q.get(), timeout=60)
                except asyncio.TimeoutError:
                    break
                events.append(ev)
                q.task_done()
                if ev.kind in (EventKind.TASK_COMPLETED,
                               EventKind.TASK_FAILED,
                               EventKind.TASK_CANCELLED):
                    # 记录已完成，但继续等一会儿（捕获 takeover/resume 后续事件）
                    stop_signal.set()
                    try:
                        ev2 = await asyncio.wait_for(q.get(), timeout=5)
                        events.append(ev2)
                        q.task_done()
                    except asyncio.TimeoutError:
                        break
        finally:
            event_bus._subscribers.discard(q)

    collector_task = asyncio.create_task(main_collector())
    run_task = asyncio.create_task(rt.run("acl-02 real takeover"))

    # ── 4. Wait briefly, then TAKE OVER before task completes ──
    await asyncio.sleep(0.5)
    print(f"  [Event] {len(events)} events so far, taking over...")

    await rt.take_over()
    await asyncio.sleep(0.05)
    takeover_mark = len(events)  # ← mark 在这里取，就在 takeover 之后
    check("state.paused after takeover", rt.state.paused is True)
    check("state.human_override after takeover", rt.state.human_override is True)
    check("human_override_started event emitted",
          any(e.kind == EventKind.HUMAN_OVERRIDE_STARTED for e in events))

    # ── 5. Human manually edits the file ──
    print(f"  [Human] Overwriting {target_file.name}...")
    target_file.write_text(HUMAN_CONTENT, encoding="utf-8")
    print(f"  [Human] Done ({len(HUMAN_CONTENT)} chars)")

    # Verify agent doesn't touch file during takeover
    await asyncio.sleep(2.0)
    current = target_file.read_text(encoding="utf-8")
    check("human content preserved during takeover", current == HUMAN_CONTENT)

    takeover_events = [e for e in events[takeover_mark:] if e.kind in {
        EventKind.TOOL_STARTED, EventKind.ACTION_SELECTED}]
    if len(takeover_events) > 0:
        # 允许 in-flight action 的 TOOL_COMPLETED（协作式暂停），
        # 但不应出现新 ACTION_SELECTED
        new_actions = [e for e in takeover_events if e.kind == EventKind.ACTION_SELECTED]
        check("no new ACTION_SELECTED during takeover", len(new_actions) == 0,
              f"Found: {[e.kind.value for e in new_actions]}")
    else:
        check("no execution events during takeover", True)

    # ── 6. RESUME ──
    print(f"  >>> RESUME <<<")
    await rt.resume()
    await asyncio.sleep(0.05)
    check("state.paused False after resume", rt.state.paused is False)
    check("state.human_override False after resume", rt.state.human_override is False)
    check("human_override_ended event emitted",
          any(e.kind == EventKind.HUMAN_OVERRIDE_ENDED for e in events))
    check("runtime_resumed event emitted",
          any(e.kind == EventKind.RUNTIME_RESUMED for e in events))

    # ── 7. Wait for completion ──
    await asyncio.wait_for(run_task, timeout=60)
    await collector_task

    # ── 8. Verify FINAL file ──
    final = target_file.read_text(encoding="utf-8")
    print(f"\n  [Final] File ({len(final)} chars):")
    for line in final.splitlines():
        print(f"    | {line}")

    # 人工内容必须保留
    check("human edit line survives", "human edit: added debug line" in final)
    check("human hello() survives", "hello from human" in final)

    # Agent 可能追加了内容（append 模式），但不会删除人工内容
    agent_rounds = [l for l in final.splitlines() if "Agent round" in l]
    print(f"  Agent appended {len(agent_rounds)} rounds after resume")

    # ── 9. Event sequence ──
    kinds = [e.kind.value for e in events]
    for required in ["task_started", "human_override_started",
                     "human_override_ended", "runtime_resumed",
                     "task_completed"]:
        check(f"'{required}' in sequence", required in kinds)

    # 顺序验证
    for ev_a, ev_b in [("human_override_started", "human_override_ended"),
                        ("human_override_ended", "runtime_resumed")]:
        try:
            ia = kinds.index(ev_a)
            ib = kinds.index(ev_b)
            check(f"'{ev_a}' before '{ev_b}'", ia < ib, f"idx={ia} >= {ib}")
        except ValueError:
            pass

    check("task in terminal state", rt.state.is_terminal,
          f"phase={rt.state.phase}")

    # ── Summary ──
    control_events = [k for k in kinds if k in {
        "human_override_started", "human_override_ended",
        "runtime_paused", "runtime_resumed"}]
    print(f"\n  [Summary] Events: {len(events)}")
    print(f"  [Summary] Control events: {control_events}")
    print(f"  [Summary] File: {len(SEED)} (seed) -> {len(HUMAN_CONTENT)} (human) "
          f"-> {len(final)} chars (final)")
    print(f"\nACL-02 (Real): {PASS}/{PASS+FAIL} passed")

    # Cleanup
    import shutil
    shutil.rmtree(workspace, ignore_errors=True)

    return FAIL == 0


if __name__ == "__main__":
    result = asyncio.run(test_acl02_real_takeover())
    sys.exit(0 if result else 1)
